source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.4'

gem 'rails', '~> 6.0.0'
gem 'pg', '~> 1.1', '>= 1.1.4'
gem 'pg_search'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors', '~> 1.0', '>= 1.0.3'     # Cross-origin
# Background processing 
gem 'redis', '~> 4.1', '>= 4.1.3'
gem 'sidekiq', '~> 6.0', '>= 6.0.2'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Testing framework & helpers
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_bot_rails', '~> 5.1', '>= 5.1.1'
  gem 'shoulda-matchers', '~> 4.1', '>= 4.1.2'
  gem 'faker', '~> 2.6'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # gem 'rails-erd'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
