default: &default
  adapter: postgresql
  # host: localhost
  host: db
  encoding: unicode
  pool: 5
  user: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
