export const GET_FAMILY_DOCTOR_PATIENTS = 'GET_FAMILY_DOCTOR_PATIENTS'
export const SET_FAMILY_DOCTOR_PATIENT = 'SET_FAMILY_DOCTOR_PATIENT'
export const SET_FAMILY_DOCTOR_CLINICIAN = 'SET_FAMILY_DOCTOR_CLINICIAN'
export const SEARCH_FAMILY_DOCTOR_PATIENTS = 'SEARCH_FAMILY_DOCTOR_PATIENTS'
export const GET_FAMILY_DOCTOR_UNFILLED_FORMS =
  'GET_FAMILY_DOCTOR_UNFILLED_FORMS'
export const SET_FAMILY_DOCTOR_FORM = 'SET_FAMILY_DOCTOR_FORM'
export const GET_CLINICIANS = 'GET_CLINICIANS'
export const REQUEST_FORM = "REQUEST_FORM"
